name: 'Create release notes'
author: 'Vitalii Kalinbet <vitalii.kalinbet@gmail.com>'

inputs:
  myToken:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
