name: 'Create release notes'
author: 'Vitalii Kalinbet <vitalii.kalinbet@gmail.com>'

inputs:
  myToken:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
  fromTag:
    description: 'The name of the release with status latest, when release branch merged in master'
    default: ''
    required: false
  toTag:
    description: 'The name of the last release with status pre-release or another not origin release'
    default: ''
    required: false

outputs:
  changelog:
    description: 'Markdown formatted changelog'

runs:
  using: 'node16'
  main: 'dist/index.js'
